version: 2

sources:
  - name: jaffle_shop
    database: raw
    description: This is the schema for Jaffle Shop Mart
    tables:
      - name: orders
      - name: customers

  - name: stripe
    description: This is the schema for payment raw data
    database: raw
    freshness: # default freshness
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: _batched_at_
    tables:
      - name: payment
        columns:
          - name: status
            tests:
             - accepted_values:
                 values: ['success', 'fail']