version: 2

sources:
  - name: ticket_tailor
    database: raw
    description: This is the schema for Ticket Orders
    tables:
      - name: orders
      - name: events
      - name: issued_tickets